In [47]:
addition <- function(a, b){
    if (length(a) != length(b)) 0
    my_list <- c()
    for (i in 1:length(a)) {
        my_list[i] <- a[i] + b[i]
    }
    my_list
}

In [49]:
scalar.mult <- function(a, b) {
    result = c()
    for (i in 1:length(b)) {
        result[i] <- a * b[i]
    }
    result
}

In [60]:
dot.product <- function(a, b) {
    result = 0
    for (i in 1:length(a)) {
        result <- result + a[i] * b[i]
    }
    result
}

In [57]:
c1 <- c(1,2,3,4,5)
c2 <- c(1,1,1,1,1)
x <- addition(c1,c2); x

[1] 2 3 4 5 6

In [58]:
x <- scalar.mult(2, c1); x

[1]  2  4  6  8 10

In [61]:
x <- dot.product(c1,c2); x

[1] 15

In [79]:
matrix.addition <- function(a, b){
    long.c <- c()
    counter <- 1
    for (row in 1:nrow(a)) {
        for (col in 1:ncol(a)) {
            long.c[counter] <- a[row, col] + b[row, col]
            counter <- counter + 1
        }
    }
    matrix(long.c, nrow(a), ncol(a), TRUE)
}

In [131]:
matrix.mul <- function(a, b){
    if (!ncol(a) == nrow(b)) {
        0
    } else {
        result <- matrix(0, nrow(a), ncol(b))

        for (row in 1:nrow(a)) {

            for (b_col in 1:ncol(b)) {

                 for (col in 1:ncol(a)) {
                     result[row, b_col] <- result[row, b_col] + (a[row, col] * b[col, b_col])
                }

            }

        }
        result
    }
}

In [134]:
matrix.transpose <- function(a){
    result = matrix(0, ncol(a), nrow(a))
    for (col in 1:ncol(a)){
        result[col,] = a[,col]
    }
    result   
}

In [135]:
m1 <- matrix(c(1,2,3,4,5,6), 3); m1
m2 <- matrix(c(1,2,3,4,5,6), 3)

x <- matrix.addition(m1, m2); x
x <- matrix.mul(m1, m2); x
x <- matrix.transpose(m1); x

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1] [,2]
[1,] 2     8  
[2,] 4    10  
[3,] 6    12

[1] 0

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6