In [1]:
addition <- function(a, b){
    if (length(a) != length(b)) 0
    my_list <- c()
    for (i in 1:length(a)) {
        my_list[i] <- a[i] + b[i]
    }
    my_list
}

In [2]:
scalar.mult <- function(a, b) {
    result = c()
    for (i in 1:length(b)) {
        result[i] <- a * b[i]
    }
    result
}

In [3]:
dot.product <- function(a, b) {
    result = 0
    for (i in 1:length(a)) {
        result <- result + a[i] * b[i]
    }
    result
}

In [4]:
c1 <- c(1,2,3,4,5)
c2 <- c(1,1,1,1,1)
x <- addition(c1,c2); x

[1] 2 3 4 5 6

In [5]:
x <- scalar.mult(2, c1); x

[1]  2  4  6  8 10

In [6]:
x <- dot.product(c1,c2); x

[1] 15

In [7]:
matrix.addition <- function(a, b){
    long.c <- c()
    counter <- 1
    for (row in 1:nrow(a)) {
        for (col in 1:ncol(a)) {
            long.c[counter] <- a[row, col] + b[row, col]
            counter <- counter + 1
        }
    }
    matrix(long.c, nrow(a), ncol(a), TRUE)
}

In [8]:
matrix.mul <- function(a, b){
    if (!ncol(a) == nrow(b)) {
        0
    } else {
        result <- matrix(0, nrow(a), ncol(b))

        for (row in 1:nrow(a)) {

            for (b_col in 1:ncol(b)) {

                 for (col in 1:ncol(a)) {
                     result[row, b_col] <- result[row, b_col] + (a[row, col] * b[col, b_col])
                }

            }

        }
        result
    }
}

In [9]:
matrix.transpose <- function(a){
    result = matrix(0, ncol(a), nrow(a))
    for (col in 1:ncol(a)){
        result[col,] = a[,col]
    }
    result   
}

In [22]:
m1 <- matrix(c(1,2,3,4,5,6), 3); m1
m2 <- matrix(c(1,2,3,4,5,6), 3)

x <- matrix.addition(m1, m2); x
x <- matrix.mul(m1, matrix.transpose(m2)); x
m1 %*% matrix.transpose(m2)
x <- matrix.transpose(m1); x

[,1] [,2]
[1,] 1    4   
[2,] 2    5   
[3,] 3    6

[,1] [,2]
[1,] 2     8  
[2,] 4    10  
[3,] 6    12

[,1] [,2] [,3]
[1,] 17   22   27  
[2,] 22   29   36  
[3,] 27   36   45

[,1] [,2] [,3]
[1,] 17   22   27  
[2,] 22   29   36  
[3,] 27   36   45

[,1] [,2] [,3]
[1,] 1    2    3   
[2,] 4    5    6

In [51]:
m <- matrix(c(3,1,2,6,4,4, 3,4,7), 3, 3);
m1 <- matrix(c(3,1,2,6,4,4,3,4,7,1,2,3), 3, 4);
m2 <- matrix(c(3,1,2,6,4,4,3,4,7,1,2,3), 4, 3);
m.zeros <- matrix(c(0,1,2,1,0,2,1,2,0), 3, 3)
print(m.zeros)


     [,1] [,2] [,3]
[1,]    0    1    1
[2,]    1    0    2
[3,]    2    2    0


In [6]:
#multiplies r-th row of M by factor
matrix.row.divide <- function( M, r, factor) {
    M[r,] = M[r,] * factor
    M #return
}

In [7]:
#adds to i-th row tje j-th row multiplied by factor
matrix.add.raw <- function(i, j, factor, M) {
    M[i,] <- M[i,] + M[j,] * factor
    M # return
}

In [8]:
# swap the i-th row with the j-th raw
matrix.swap.raw <- function(i, j, M) {
    tmp <- M[i,]
    M[i,] <- M[j,]
    M[j,] <- tmp
    M
}

In [9]:
m.swaped <- matrix.swap.raw(1,2,m)
print(m)
print(m.swaped)

     [,1] [,2] [,3]
[1,]    3    6    3
[2,]    1    4    4
[3,]    2    4    7
     [,1] [,2] [,3]
[1,]    1    4    4
[2,]    3    6    3
[3,]    2    4    7


In [113]:
#general Gauss row reduction algorithm
# what if the matrix will be 2x10 dimension (it's ok for me no it's not) what if 10x2
matrix.eliminate <- function(m){
    border = min(c(nrow(m), ncol(m)))
    for (ic in 1:border){
        # find the index of max absolute value in column and swap rows
        to.swap <- which(m[ic:nrow(m),ic] == max(abs(m[ic:nrow(m),ic]))) + ic - 1
        m <- matrix.swap.raw(ic, to.swap[1], m)
        # makes one on the diagonal
        m <- matrix.row.divide(m, ic, 1/m[ic,ic]) #TODO fix the case m[1,1] == 0
        if (ic + 1 > nrow(m)) break
        for (ir in (ic+1):nrow(m)){
            m <- matrix.add.raw(ir, ic,-m[ir,ic], m)    
        }        
    }
    m
}

In [114]:
print("m original")
print(m)
me <- matrix.eliminate(m)
print(me)

print("m1 original")
print(m1)
m1e <- matrix.eliminate(m1)
print(m1e)
print("m2 original")
print(m2)
m2e <- matrix.eliminate(m2)
print(m2e)

print("m.zeros original")
print(m.zeros)
m.zeros.e <- matrix.eliminate(m.zeros)
print(m.zeros.e)
# md <- matrix.row.divide(m, 1, 1/3)
# print(md)

# ma <- matrix.add.raw(2, 1, -2, md)
# print(ma)

[1] "m original"
     [,1] [,2] [,3]
[1,]    3    6    3
[2,]    1    4    4
[3,]    2    4    7
     [,1] [,2] [,3]
[1,]    1    2  1.0
[2,]    0    1  1.5
[3,]    0    0  1.0
[1] "m1 original"
     [,1] [,2] [,3] [,4]
[1,]    3    6    3    1
[2,]    1    4    4    2
[3,]    2    4    7    3
     [,1] [,2] [,3]      [,4]
[1,]    1    2  1.0 0.3333333
[2,]    0    1  1.5 0.8333333
[3,]    0    0  1.0 0.4666667
[1] "m2 original"
     [,1] [,2] [,3]
[1,]    3    4    7
[2,]    1    4    1
[3,]    2    3    2
[4,]    6    4    3
     [,1]      [,2] [,3]
[1,]    1 0.6666667 0.50
[2,]    0 1.0000000 0.15
[3,]    0 0.0000000 1.00
[4,]    0 0.0000000 0.00
[1] "m.zeros original"
     [,1] [,2] [,3]
[1,]    0    1    1
[2,]    1    0    2
[3,]    2    2    0
     [,1] [,2] [,3]
[1,]    1    1    0
[2,]    0    1    1
[3,]    0    0    1


In [112]:
print(m)
m[2:nrow(m),1]

     [,1] [,2] [,3]
[1,]    3    6    3
[2,]    1    4    4
[3,]    2    4    7


[1] 1 2