In [1]:
# small dataset
set.seed(212)
Data = matrix(rnorm(30), 10, 3)

Data

[,1]       [,2]        [,3]       
 [1,] -0.2391731  0.15034879  0.55113696
 [2,]  0.6769356  0.50967649  1.21557683
 [3,] -2.4403360 -0.77331482 -0.60781873
 [4,]  1.2408845  1.87566596  1.35475360
 [5,] -0.3265144  0.78830571 -1.33758388
 [6,]  0.1544909 -2.30671309 -0.79244866
 [7,]  1.0368712 -1.37584147 -1.02442868
 [8,] -0.7796077 -1.02111184 -0.02768991
 [9,]  0.6212641 -1.37921485 -0.61268087
[10,]  0.2994313 -0.03476825  0.16605702

In [2]:
# centering with 'scale()'
center_scale <- function(x) {
    scale(x, scale = FALSE)
}

# apply it
Data <- center_scale(Data)

In [3]:
pca.1 <- eigen(cov(Data))
pca.2 <- svd(Data)
print(pca.1)
print(pca.2)

eigen() decomposition
$values
[1] 2.1502355 1.0035836 0.3943153

$vectors
           [,1]        [,2]       [,3]
[1,] -0.3733788  0.91006959 -0.1798933
[2,] -0.7723187 -0.41237480 -0.4831882
[3,] -0.5139183 -0.04147729  0.8568358

$d
[1] 4.399104 3.005371 1.883836

$u
            [,1]        [,2]        [,3]
 [1,]  0.1440581  0.15853952  0.19651549
 [2,]  0.3625205 -0.06039715  0.31907987
 [3,] -0.3403220  0.68235028  0.11648889
 [4,]  0.6664622 -0.04181722 -0.02183565
 [5,]  0.0279996  0.24645712 -0.81783224
 [6,] -0.4108599 -0.31635046  0.17802845
 [7,] -0.1996413 -0.45902216 -0.25050631
 [8,] -0.1750972  0.15346328  0.28532199
 [9,] -0.1874068 -0.32795064 -0.02267588
[10,]  0.1122868 -0.03527257  0.01741539

$v
          [,1]        [,2]       [,3]
[1,] 0.3733788 -0.91006959 -0.1798933
[2,] 0.7723187  0.41237480 -0.4831882
[3,] 0.5139183  0.04147729  0.8568358



In [4]:
check_equal <-  function(M, v, e) {
    n <- nrow(M) - 1
    v^2/n
}

check_equal(Data, pca.2$d, pca.1$values)

[1] 2.1502355 1.0035836 0.3943153

In [12]:
prco <- prcomp(Data)
print(prco$sdev^2)
print(prco$rotation)

[1] 2.1502355 1.0035836 0.3943153
           PC1         PC2        PC3
[1,] 0.3733788 -0.91006959 -0.1798933
[2,] 0.7723187  0.41237480 -0.4831882
[3,] 0.5139183  0.04147729  0.8568358


In [7]:
library(FactoMineR)

ERROR: Error in library(FactoMineR): there is no package called ‘FactoMineR’


In [6]:
PCA(Data)

ERROR: Error in PCA(Data): could not find function "PCA"


In [17]:
?PCA()

PCA                 package:FactoMineR                 R Documentation

_P_r_i_n_c_i_p_a_l _C_o_m_p_o_n_e_n_t _A_n_a_l_y_s_i_s (_P_C_A)

_D_e_s_c_r_i_p_t_i_o_n:

     Performs Principal Component Analysis (PCA) with supplementary
     individuals, supplementary quantitative variables and
     supplementary categorical variables.
     Missing values are replaced by the column mean.

_U_s_a_g_e:

     PCA(X, scale.unit = TRUE, ncp = 5, ind.sup = NULL, 
         quanti.sup = NULL, quali.sup = NULL, row.w = NULL, 
         col.w = NULL, graph = TRUE, axes = c(1,2))
     
_A_r_g_u_m_e_n_t_s:

       X: a data frame with _n_ rows (individuals) and _p_ columns
          (numeric variables)

     ncp: number of dimensions kept in the results (by default 5)

scale.unit: a boolean, if TRUE (value set by default) then data are
          scaled to unit variance

 ind.sup: a vector indicating the indexes of the supplementary
          individuals

quanti.sup: a vector indicating the indexes of the quantitative
          supplementary variables

quali.sup: a vector indicating the indexes of the categorical
          supplementary variables

   row.w: an optional row weights (by default, a vector of 1 for
          uniform row weights); the weights are given only for the
          active individuals

   col.w: an optional column weights (by default, uniform column
          weights); the weights are given only for the active variables

   graph: boolean, if TRUE a graph is displayed

    axes: a length 2 vector specifying the components to plot

_V_a_l_u_e:

     Returns a list including:

     eig: a matrix containing all the eigenvalues, the percentage of
          variance and the cumulative percentage of variance

     var: a list of matrices containing all the results for the active
          variables (coordinates, correlation between variables and
          axes, square cosine, contributions)

     ind: a list of matrices containing all the results for the active
          individuals (coordinates, square cosine, contributions)

 ind.sup: a list of matrices containing all the results for the
          supplementary individuals (coordinates, square cosine)

quanti.sup: a list of matrices containing all the results for the
          supplementary quantitative variables (coordinates,
          correlation between variables and axes)

quali.sup: a list of matrices containing all the results for the
          supplementary categorical variables (coordinates of each
          categories of each variables, v.test which is a criterion
          with a Normal distribution, and eta2 which is the square
          correlation corefficient between a qualitative variable and a
          dimension)
     Returns the individuals factor map and the variables factor map.
     The plots may be improved using the argument autolab, modifying
     the size of the labels or selecting some elements thanks to the
     'plot.PCA' function.

_A_u_t_h_o_r(_s):

     Francois Husson <email: Francois.Husson@agrocampus-ouest.fr>,
     Jeremy Mazet

_R_e_f_e_r_e_n_c_e_s:

     Husson, F., Le, S. and Pages, J. (2010). Exploratory Multivariate
     Analysis by Example Using R, _Chapman and Hall_.

_S_e_e _A_l_s_o:

     'print.PCA', 'summary.PCA', 'plot.PCA', 'dimdesc',
     Video showing how to perform PCA with FactoMineR

_E_x_a_m_p_l_e_s:

     data(decathlon)
     res.pca <- PCA(decathlon, quanti.sup = 11:12, quali.sup=13)
     ## plot of the eigenvalues
     ## barplot(res.pca$eig[,1],main="Eigenvalues",names.arg=1:nrow(res.pca$eig))
     summary(res.pca)
     plot(res.pca,choix="ind",habillage=13)
     dimdesc(res.pca, axes = 1:2)
     ## To draw ellipses around the categories of the 13th variable (which is categorical)
     plotellipses(res.pca,13)
     
     ## Example with missing data
     ## use package missMDA
     ## Not run:
     
     require(missMDA)
     data(ora

In [18]:
?prcomp

prcomp                  package:stats                  R Documentation

_P_r_i_n_c_i_p_a_l _C_o_m_p_o_n_e_n_t_s _A_n_a_l_y_s_i_s

_D_e_s_c_r_i_p_t_i_o_n:

     Performs a principal components analysis on the given data matrix
     and returns the results as an object of class 'prcomp'.

_U_s_a_g_e:

     prcomp(x, ...)
     
     ## S3 method for class 'formula'
     prcomp(formula, data = NULL, subset, na.action, ...)
     
     ## Default S3 method:
     prcomp(x, retx = TRUE, center = TRUE, scale. = FALSE,
            tol = NULL, rank. = NULL, ...)
     
     ## S3 method for class 'prcomp'
     predict(object, newdata, ...)
     
_A_r_g_u_m_e_n_t_s:

 formula: a formula with no response variable, referring only to
          numeric variables.

    data: an optional data frame (or similar: see 'model.frame')
          containing the variables in the formula 'formula'.  By
          default the variables are taken from 'environment(formula)'.

  subset: an optional vector used to select rows (observations) of the
          data matrix 'x'.

na.action: a function which indicates what should happen when the data
          contain 'NA's.  The default is set by the 'na.action' setting
          of 'options', and is 'na.fail' if that is unset. The
          'factory-fresh' default is 'na.omit'.

     ...: arguments passed to or from other methods.  If 'x' is a
          formula one might specify 'scale.' or 'tol'.

       x: a numeric or complex matrix (or data frame) which provides
          the data for the principal components analysis.

    retx: a logical value indicating whether the rotated variables
          should be returned.

  center: a logical value indicating whether the variables should be
          shifted to be zero centered. Alternately, a vector of length
          equal the number of columns of 'x' can be supplied.  The
          value is passed to 'scale'.

  scale.: a logical value indicating whether the variables should be
          scaled to have unit variance before the analysis takes place.
          The default is 'FALSE' for consistency with S, but in general
          scaling is advisable.  Alternatively, a vector of length
          equal the number of columns of 'x' can be supplied.  The
          value is passed to 'scale'.

     tol: a value indicating the magnitude below which components
          should be omitted. (Components are omitted if their standard
          deviations are less than or equal to 'tol' times the standard
          deviation of the first component.)  With the default null
          setting, no components are omitted (unless 'rank.' is
          specified less than 'min(dim(x))'.).  Other settings for tol
          could be 'tol = 0' or 'tol = sqrt(.Machine$double.eps)',
          which would omit essentially constant components.

   rank.: optionally, a number specifying the maximal rank, i.e.,
          maximal number of principal components to be used.  Can be
          set as alternative or in addition to 'tol', useful notably
          when the desired rank is considerably smaller than the
          dimensions of the matrix.

  object: object of class inheriting from '"prcomp"'

 newdata: An optional data frame or matrix in which to look for
          variables with which to predict.  If omitted, the scores are
          used.  If the original fit used a formula or a data frame or
          a matrix with column names, 'newdata' must contain columns
          with the same names. Otherwise it must contain the same
          number of columns, to be used in the same order.

_D_e_t_a_i_l_s:

     The calculation is done by a singular value decomposition of the
     (centered and possibly scaled) data matrix, not by using 'eigen'
     on the covariance matrix.  This is generally the preferred method
     for numerical accuracy.  The 'print' method for these objects
     prints the results in a nice format and the 'p

In [19]:
?princomp

princomp                 package:stats                 R Documentation

_P_r_i_n_c_i_p_a_l _C_o_m_p_o_n_e_n_t_s _A_n_a_l_y_s_i_s

_D_e_s_c_r_i_p_t_i_o_n:

     'princomp' performs a principal components analysis on the given
     numeric data matrix and returns the results as an object of class
     'princomp'.

_U_s_a_g_e:

     princomp(x, ...)
     
     ## S3 method for class 'formula'
     princomp(formula, data = NULL, subset, na.action, ...)
     
     ## Default S3 method:
     princomp(x, cor = FALSE, scores = TRUE, covmat = NULL,
              subset = rep_len(TRUE, nrow(as.matrix(x))), fix_sign = TRUE, ...)
     
     ## S3 method for class 'princomp'
     predict(object, newdata, ...)
     
_A_r_g_u_m_e_n_t_s:

 formula: a formula with no response variable, referring only to
          numeric variables.

    data: an optional data frame (or similar: see 'model.frame')
          containing the variables in the formula 'formula'.  By
          default the variables are taken from 'environment(formula)'.

  subset: an optional vector used to select rows (observations) of the
          data matrix 'x'.

na.action: a function which indicates what should happen when the data
          contain 'NA's.  The default is set by the 'na.action' setting
          of 'options', and is 'na.fail' if that is unset. The
          'factory-fresh' default is 'na.omit'.

       x: a numeric matrix or data frame which provides the data for
          the principal components analysis.

     cor: a logical value indicating whether the calculation should use
          the correlation matrix or the covariance matrix.  (The
          correlation matrix can only be used if there are no constant
          variables.)

  scores: a logical value indicating whether the score on each
          principal component should be calculated.

  covmat: a covariance matrix, or a covariance list as returned by
          'cov.wt' (and 'cov.mve' or 'cov.mcd' from package 'MASS').
          If supplied, this is used rather than the covariance matrix
          of 'x'.

fix_sign: Should the signs of the loadings and scores be chosen so that
          the first element of each loading is non-negative?

     ...: arguments passed to or from other methods. If 'x' is a
          formula one might specify 'cor' or 'scores'.

  object: Object of class inheriting from '"princomp"'.

 newdata: An optional data frame or matrix in which to look for
          variables with which to predict.  If omitted, the scores are
          used.  If the original fit used a formula or a data frame or
          a matrix with column names, 'newdata' must contain columns
          with the same names. Otherwise it must contain the same
          number of columns, to be used in the same order.

_D_e_t_a_i_l_s:

     'princomp' is a generic function with '"formula"' and '"default"'
     methods.

     The calculation is done using 'eigen' on the correlation or
     covariance matrix, as determined by 'cor'.  This is done for
     compatibility with the S-PLUS result.  A preferred method of
     calculation is to use 'svd' on 'x', as is done in 'prcomp'.

     Note that the default calculation uses divisor 'N' for the
     covariance matrix.

     The 'print' method for these objects prints the results in a nice
     format and the 'plot' method produces a scree plot ('screeplot').
     There is also a 'biplot' method.

     If 'x' is a formula then the standard NA-handling is applied to
     the scores (if requested): see 'napredict'.

     'princomp' only handles so-called R-mode PCA, that is feature
     extraction of variables.  If a data matrix is supplied (possibly
     via a formula) it is required that there are at least as many
     units as variables.  For Q-mode PCA use 'prcomp'.

_V_a_l_u_e:

     'princomp' returns a list with class '"princomp"' containing the
     following components:

    sdev: the standard dev